on:
  push:
    tags:
      - v*.*.*

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Update semantic versioning
    steps:
      - uses: actions/checkout@v2
      - uses: gnclmorais/update-semver-action@v1
